# Generated by Django 5.2.6 on 2025-10-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='charac_hp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='charac_hp',
        ),
    ]
