# Generated by Django 5.2.6 on 2025-10-31 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_npc_charac_hp_remove_player_charac_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='players',
        ),
        migrations.AddField(
            model_name='attribute',
            name='player',
            field=models.OneToOneField(blank=True, help_text='The player linked to this attribute block.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='characters.player'),
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='npcs',
        ),
        migrations.AddField(
            model_name='attribute',
            name='npcs',
            field=models.OneToOneField(blank=True, help_text='NPC in the game.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='characters.npc'),
        ),
    ]
