# Generated by Django 5.2.6 on 2025-10-17 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_theme', models.CharField(choices=[('FANTASY', 'Fantasy'), ('HORROR', 'Horror'), ('SCI_FI', 'Science Fiction'), ('HISTORICAL', 'Historical'), ('CUSTOM', 'Custom')], default='FANTASY', help_text='Game theme', max_length=20)),
                ('game_started_on', models.DateTimeField(auto_now_add=True)),
                ('game_master_id', models.ForeignKey(help_text='Current GM for this game', on_delete=django.db.models.deletion.PROTECT, related_name='games_mastered', to=settings.AUTH_USER_MODEL)),
                ('npcs', models.ManyToManyField(blank=True, help_text='NPC in the game.', related_name='games', to='characters.npc')),
                ('players', models.ManyToManyField(blank=True, help_text='Players in the game.', related_name='games', to='characters.player')),
            ],
            options={
                'db_table': 'games',
                'indexes': [models.Index(fields=['game_name'], name='games_game_na_304dce_idx'), models.Index(fields=['game_theme'], name='games_game_th_1e4540_idx')],
                'constraints': [models.UniqueConstraint(fields=('game_name', 'game_master_id'), name='unique_game_name_per_master')],
            },
        ),
    ]
