# Generated by Django 5.2.6 on 2025-11-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_model',
            field=models.CharField(choices=[('DND', 'Dungeons & Dragons'), ('CTHU', 'Call of Cthulhu'), ('BRIG', 'Brigandyne'), ('DCC', 'Dungeon Crawler Classic'), ('HMB', 'Homebrew system')], default='DND', max_length=10),
        ),
    ]
